name: 'on-demand-codebuild'

on:
  workflow_dispatch:
    inputs:
      suite:
        requred: true

jobs:
  on-demand-test:
    name: 'on-demand-automation'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:
            required: false
          aws-secret-access-key:
            required: false
          aws-session-token:
            required: false
          aws-region: eu-central-1
      - name: Run i-test-automation
        uses: aws-actions/aws-codebuild-run-build@v1.0.3
        with:
          project-name: i-test-automation
          buildspec-override: buildspec.yml
